runtime: nodejs12
env: standard
instance_class: B2
handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: '301'
  - url: .*
    script: auto
env_variables:
  NODE_ENV: production
manual_scaling:
  instances: 1