runtime: nodejs10
env: standard
handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10