export const CELL_MIN_SIZE = 3
export const CELL_SIZE_INCREMENT_INTERVAL = 1

//DYNAMIC CALCULATION INPUT CONSTS
export const MIN_NUMBER_OF_CELLS_HORIZONTALLY = 9

//3D Related
export const DEFAULT_Z_DISTANCE = 300
export const ZOOM_MULTIPLIER_DEFAULT = 150